language: node_js
node_js:
  - "6"
  - "8"
  - "9"
before_script:
  - npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
 
cache: yarn
install:
- yarn install
- yarn global add coveralls


script:
  - npm run-script build
  - npm run-script lint
  - yarn jest --coverage --coverageReporters=text-lcov | coveralls

